# Namespace (Para tener ordenado el proyecto)
apiVersion: v1
kind: Namespace
metadata:
  name: blackfriday
---
# ==========================================
# COMPONENTE 1: SERVIDOR GO (Backend)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-go
  namespace: blackfriday
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-server-go
  template:
    metadata:
      labels:
        app: grpc-server-go
    spec:
      containers:
      - name: grpc-server-go
        image: <direccion IP del registry privado>:5000/grpc-server-go:v2
        ports:
        - containerPort: 50051
        env:
        - name: KAFKA_BROKER
          value: "my-cluster-kafka-bootstrap:9092"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
---
# Servicio Interno para que Rust encuentre a Go
apiVersion: v1
kind: Service
metadata:
  name: grpc-go-service 
  namespace: blackfriday
spec:
  selector:
    app: grpc-server-go
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
---
# ==========================================
# COMPONENTE 2: API RUST (Frontend)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rust
  namespace: blackfriday
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rust
  template:
    metadata:
      labels:
        app: api-rust
    spec:
      containers:
      - name: api-rust
        image: <direccion IP del registry privado>:5000/api-rust:v3
        ports:
        - containerPort: 8080
        env:
        - name: BIND_ADDR
          value: "<direccion IP de escucha>"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
---

# Servicio Interno (NGINX le enviará el tráfico aquí)
apiVersion: v1
kind: Service
metadata:
  name: api-rust-service
  namespace: blackfriday
spec:
  selector:
    app: api-rust
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 8080 
  type: ClusterIP 
