apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-client
  namespace: blackfriday
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-http-client
  template:
    metadata:
      labels:
        app: go-http-client
    spec:
      containers:
      - name: go-http-client
        image: <direccion IP del registry privado>:5000/go-http-client:v1
        ports:
        - containerPort: 3000
        env:
        - name: GRPC_SERVER_HOST
          value: "grpc-go-service:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: go-http-service
  namespace: blackfriday
spec:
  selector:
    app: go-http-client
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP