apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-rust-hpa
  namespace: blackfriday
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-rust
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30